[tool.poetry]
name = "science-optimization"
version = "9.0.1"
description = "A framework for optimization."
authors = ["Matheus Mendon√ßa <matheus.mendonca@enacom.com.br>"]
readme = "README.md"
packages = [
    {include = "science_optimization"},
    {include = "src"}    
]
build = "build.py"

[tool.poetry.dependencies]
python = ">= 3.8, < 3.12"
cycler = ">=0.11,<1.0"
decorator = ">=5.1,<6.0"
joblib = ">=1.1,<2.0"
kiwisolver = ">=1.3,<2.0"
matplotlib = ">=3.4,<4.0"
networkx = ">=2.6,<3.0"
numpy = ">=1.21,<2.0"
ortools = ">=9.6,<10.0"
pandas = ">=1.3,<2.0"
pillow = ">=9.3,<10.0"
protobuf = ">=4.22,<5.0"
pyparsing = ">=3.0,<4.0"
python-dateutil = ">=2.8,<3.0"
pytz = ">=2021.3,<2022.0"
pywavelets = ">=1.1,<2.0"
scipy = ">=1.10,<2.0"
six = ">=1.16,<2.0"
xlrd = ">=2.0,<3.0"
pybind11 = "^2.10.4"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-xdist = "^2.5.0"
pytest-clarity = "^1.0.1"
mutmut = "^2.4.1"

[build-system]
requires = ["poetry-core", "setuptools", "pybind11"]
build-backend = "poetry.core.masonry.api"