[tool.poetry]
name = "cupid_matching"
version = "1.0.5"
description = "Solves, simulates, and estimates separable matching TU models"
authors = ["Bernard Salanie <bsalanie@columbia.edu>"]
readme = "README.md"
packages = [{include = "cupid_matching"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.20"
scipy = "^1.8"
matplotlib = "^3.6"
seaborn = "^0.12"
altair = "^4.2"
pandas = "^1.4"
scikit-learn = "^1.1"
streamlit = "^1.20"
watchdog = "^3.0"

[tool.poetry.dev-dependencies]
pip = "^23.0"
wheel = "^0.35"
black = "*"
flake8 = "*"
pytest = "^7.0"
mypy = "^1.0"
mkdocs = "*"
mkdocs-material = "*"
mkdocstrings = "*"
mkdocstrings-python = "^0.8"
markdown = "*"
pymdown-extensions = "*"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 80
target_version = ["py310"]

[tool.isort]
profile = "black"
py_version = 310
multi_line_output = 3
