[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dolby"
version = "0.0.4"
authors = [
  { name="Gautam Veldanda", email="gautamveldanda@gmail.com" },
]
description = "A Python library for Dolby AI"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "selenium",
  "beautifulsoup4",
  "icrawler",
  "openai",
  "requests",
  "googletrans"
]
[project.urls]
"Homepage" = "https://github.com/gautamveldanda/dolby"