[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "singular-client"
version = "0.1.3"
python_requires = ">=3.8"
description = "Singular API client"
authors = [
    {name = "Ryan Young", email = "dev@ryayoung.com"}
]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/ryayoung/singular-client"
repository = "https://github.com/ryayoung/singular-client"
documentation = "https://singular-client.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.8",
]
dependencies = [
    'requests',
]
