[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tdbug"
version = "1.0.5"
authors = [
  { name="Damon Pickett", email="damon.pickett@gmail.com" },
]
description = "tdbug is a command-line application that uses the OpenAI API to diagnose bugs when programming."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/damonpickett/tdbug"
"Bug Tracker" = "https://github.com/damonpickett/tdbug/issues"