[build-system]
requires = ["setuptools >= 67"]
build-backend = "setuptools.build_meta"

[project]
name = "twitscrape"
version = "0.0.6"
authors = [
  { name="Christian Harrison", email="christywastakenwastaken@gmail.com" },
]
description = "Simple package using Selenium to scrape tweet data based on geolocation and datetime"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "selenium-wire >= 5.1.0",
    "pandas >= 1.5.3",
    "webdriver-manager >= 3.8.5",
]

[project.urls]
"Homepage" = "https://github.com/christywastaken/twitscrape"
"Bug Tracker" = "https://github.com/christywastaken/twitscrape/issues"

