[tool.poetry]
name = "fastapi-myhelper"
version = "0.1.5.2"
description = ""
authors = ["MihaTeam1 <sarsern2004@gmail.com>"]
packages = [{include = "fastapi_myhelper"}]

[tool.poetry.dependencies]
python = "^3.9"
strawberry-graphql = {version = "^0.155.3", optional = true}
sqlmodel = {version = "^0.0.8", optional = true}
sqlalchemy = {version = ">=1.4.17,<=1.4.41", optional = true}
pydantic = {version = "^1.10.4", optional = true}

[tool.poetry.extras]
all = [
    'sqlmodel',
    'strawberry-graphql'
]
strawberry = ['strawberry-graphql']
sqlmodel = ['sqlmodel', 'pydantic', 'sqlalchemy']
sqlalchemy = ['sqlalchemy']
pydantic = ['pydantic']


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
