[tool.poetry]
name = "nlp2cron"
version = "0.1.0"
description = "Nature language to cron"
authors = ["quqinglei <quqinglei@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
cn2an = "^0.5.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
