[project]
name = "pydisort"
version = "0.0.1"
authors = [
  { name="Zoey Hu", email="zoey.zyhu@gmail.com" },
]
description = "Scientific computing to the next level."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

