[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "narcapi"
version = "0.0.1"
authors = [
  { name="ApolloDev", email="apollodev@goapollo.ai" },
]
description = "Apollo AI NARC API package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://goapollo.ai"